#!/bin/sh

#####################
#  vars & functions #
#####################

# get default route iface
GW_IFACE="$(get_gw_iface)"

# load common functions
. /usr/share/natfree-common/natfree-common

########
# main #
########

[ "$GW_IFACE" ] || die "Unable to find network gateway iface"
[ "$IFACE" ] || die "Undefined 'IFACE' environment var. May be not running under networkd-dispatcher?"

# correct interface up?
[ "$GW_IFACE" = "$IFACE" ] || exit 0

natfree-update-server-arithmetic -i "$GW_IFACE"
exit 0

